config/routes.rb
Rails.application.routes.draw do
  resources :components do
    resources :tasks
  end
  namespace :component do
    resources :tasks
  end
  resources :user_details
  resources :teams
  resources :meetings do
    resources :logs
  end
  namespace :meeting do
    resources :logs
  end
  resources :appoiments
  resources :meetings do
    member do
      get :toggle_subscribe
      get :toggle_unsubscribe
    end
  end
  devise_for :users
  
  resources :users do
    get :search_logs
  end

  root to: "user#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :logs, dependent: :delete_all
  has_many :appoiments, dependent: :delete_all
  has_many :users, through: :appoiments
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    @log = @meeting.logs.build
    
    @meeting_logs = []
    @meeting.logs.each do |log|
      if log.persisted?
        @meeting_logs.push(log)
      end
    end
    @meeting_logs = @meeting_logs.sort_by {|log| log.date}.reverse
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Meeting was successfully created." }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Meeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_subscribe
    user_subscribe = User.find(current_user.id)
    meeting_subscribe = Meeting.find(params[:id])
    Appoiment.create(meeting:meeting_subscribe, user: user_subscribe)
    redirect_to meetings_url
  end

  def toggle_unsubscribe
    user_subscribe = User.find(current_user.id)
    meeting_subscribe = Meeting.find(params[:id])
    Appoiment.delete(Appoiment.where(meeting:meeting_subscribe, user: user_subscribe))
    redirect_back fallback_location: root_path
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :description)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |f| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class='container'>
    <div class="card">
      <div class="card-body " style="text-align: left;">
      <h3 class='card-tytle' style="text-align: center;">Adaugă ședință nouă</h3>
        <div class="mb-3">
          <%= f.label "Nume", { class: "form-label"}  %><br />
          <%= f.text_field :name, { class: "form-control", placeholder: "Meeting name" } %>
        </div>

        <div class="mb-3">
          <%= f.label "Descriere", { class: "form-label"} %><br />
          <%= f.text_area :description , { class: "form-control"} %>
        </div>

        <div class="mb-3">
          <%= f.submit "Adaugă", {class: "btn btn-primary"} %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<br>

<div class = "container">
 <div class="row">
    <div class="col d-flex justify-content-start ">
      <span class="align-middle"><h1>Toate ședințele:</h1></span>
    </div>
    <div class="col">
      <%= link_to 'Adaugă ședință', new_meeting_path, class: "btn btn-success text-light float-end"%>
    </div>
  
  <div class = "container vertical-scrollable border border-secondary">
    <div class="row my-1">
      <% @meetings.each do |meeting| %>
        <div class="card text-dark border-dark bg-light m-2" style="width: 99%;" >
            <div class="card-body">
              <div class="card-header bg-secondary">
                <div class="fw-bold"><%= meeting.name %></div>
              </div>
              <p class="card-text"><%= meeting.description %></p>
              <%= link_to 'Afișează', meeting,class: "btn btn-primary text-white btn-sm" %>
              <%= link_to 'Editează', edit_meeting_path(meeting),class: "btn btn-secondary text-white btn-sm" %>
              
              <% if Appoiment.where(meeting_id: meeting.id, user_id: current_user.id).empty? %>
                <%= link_to 'Abonare', toggle_subscribe_meeting_path(meeting), class: "btn btn-subscribe text-white btn-sm"%>
              <% else %>
                <%= link_to 'Dezabonare', toggle_unsubscribe_meeting_path(meeting), class: "btn btn-subscribe text-white btn-sm"%>
              <% end %>

              <%= link_to 'Șterge', meeting,class: "btn btn-destroy text-white btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<style> 
    .vertical-scrollable> .row {
      height: 600px;
      overflow-y: scroll; 
    }

    .btn-subscribe,
    .btn-subscribe:hover,
    .btn-subscribe:active,
    .btn-subscribe:visited,
    .btn-subscribe:focus {
      background-color: #cd201f;
      border-color: #cd201f;
  }

    .btn-destroy,
    .btn-destroy:hover,
    .btn-destroy:active,
    .btn-destroy:visited,
    .btn-destroy:focus {
      background-color: #131418;
      border-color: #131418;
  }
</style> 

app/views/meetings/new.html.erb
<br>
<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<style> 
    .vertical-scrollable> .row {
      height: 500px;
      overflow-y: scroll; 
    }
</style>

<br>
<div class="container">
  <div class="card border-secondary my-1">
    <div class="card-body">
      <div class="card-header text-light " style="background-color: #4c75a3;">
        <div class="fw-bold fs-1"><%=  @meeting.name  %></div>
      </div>
      <br>
      <h6 class="text-start"><%=@meeting.description%></h6>

      <hr>
        <%= render 'logs/form' %>
      <hr>

      <div class="card-footer">
      <div class="fs-3">Notițele ședinței</div>
      <div class="container vertical-scrollable border border-dark">
        <div class="row my-2">
          <% @meeting_logs.each do |log| %>

            <% if "critical" == log.severity %>
              <div class="card border-danger m-1"style="width: 99%;">
                <div class="card-header bg-danger text-light">
                  <div class="row">
                    <div class="col-md">
                      <div class="fw-bold fs-6"style="text-align: left;"><%= @meeting.name %></div>
                    </div>
                    <div class="col-md">
                      <div class="fw-bold fs-6"style="text-align: center;">Critic</div>
                    </div>
                    <div class="col-md">
                      <div class="fw-bold fs-6"style="text-align: right;"><%= log.date %></div>
                    </div>
                  </div>
                </div>
                <div class="card-body text-dark">
                  <h5 class="card-title"><%= log.title %></h5>
                  <p class="card-text fs-6" style="text-align: left;"><%= log.content %></p>
                </div>
              </div>
            <%end%>

            <% if "normal" == log.severity %>
              <div class="card border-info m-1"style="width: 99%;">
                <div class="card-header bg-info text-light">
                    <div class="row">
                      <div class="col-md">
                        <div class="fw-bold fs-6"style="text-align: left;"><%= @meeting.name %></div>
                      </div>
                      <div class="col-md">
                        <div class="fw-bold fs-6"style="text-align: center;">Normal</div>
                      </div>
                      <div class="col-md">
                        <div class="fw-bold fs-6"style="text-align: right;"><%= log.date %></div>
                      </div>
                  </div>
                </div>
                <div class="card-body text-dark">
                  <h5 class="card-title"><%= log.title %></h5>
                  <p class="card-text fs-6" style="text-align: left;"><%= log.content %></p>
                </div>
              </div>
            <%end%>



          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>