config/routes.rb
Rails.application.routes.draw do
  resources :components do
    resources :tasks
  end
  namespace :component do
    resources :tasks
  end
  resources :user_details
  resources :teams
  resources :meetings do
    resources :logs
  end
  namespace :meeting do
    resources :logs
  end
  resources :appoiments
  resources :meetings do
    member do
      get :toggle_subscribe
      get :toggle_unsubscribe
    end
  end
  devise_for :users
  
  resources :users do
    get :search_logs
  end

  root to: "user#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user_detail
  belongs_to :component
  accepts_nested_attributes_for :component, :user_detail

  validates :estimation, inclusion: {in: [0,1, 2, 3, 5, 8, 13, 21]} 
  validates :developer_feedback, inclusion: {in: ["underestimated", "supraestimated", "perfectly-estimated"]} 

  ESTIMATION_OPTIONS = [['0SP',0],
                      ['1SP',1],
                      ['2SP',2],
                      ['3SP',3],
                      ['5SP',5],
                      ['8SP',8],
                      ['13SP',13],
                      ['21SP',21],]
  
  DEVELOPER_FEEDBACK_OPTIONS = [["Subestimat","underestimated"],
                                ["Perfect estimat","perfectly-estimated"],
                                ["Supraestimat","supraestimated"]]


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_component
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET components/1/tasks
  def index
    @tasks = @component.tasks
  end

  # GET components/1/tasks/1
  def show
    # Feedback estimation 
    case @task.developer_feedback
      when "perfectly-estimated"
        @feedback_task = "Estimată corespunzător"
      when "supraestimated"
        @feedback_task = "Supraestimată"
      when "underestimated"
        @feedback_task = "Subestimată"
      else
        @feedback_task = "Nu există activități"
    end 
    
    # Team of the developer
    @team = Team.find(Component.find(@task.component_id).team_id)

    # Responsable developer 
    @developer = UserDetail.find(@task.user_detail_id)

  end

  # GET components/1/tasks/new
  def new
    @task = @component.tasks.build
  end

  # GET components/1/tasks/1/edit
  def edit
    @current_user_details = UserDetail.where(user_id: current_user.id).first
  end

  # POST components/1/tasks
  def create
    @task = @component.tasks.build(task_params)

    if @task.save
      redirect_to(@task.component)
    else
      render action: 'new'
    end
  end

  # PUT components/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to([@task.component, @task], notice: 'Task was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE components/1/tasks/1
  def destroy
    @task.destroy

    redirect_to component_tasks_url(@component)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component
      @component = Component.find(params[:component_id])
    end

    def set_task
      @task = @component.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :description, :first_commit, :last_commit, :estimation, :developer_feedback, :user_detail_id, :component_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.component, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='container'>
    <div class="card">
      <div class="card-body " style="text-align: left;">
      <h3 class='card-tytle' style="text-align: center;">Adaugă activitate</h3>
        <div class="mb-3">
          <%= f.label "Denumire", { class: "form-label"}  %><br />
          <%= f.text_field :title, { class: "form-control", placeholder: "Denumire activitate..." } %>
        </div>

        <div class="mb-3">
          <%= f.label "Descriere", { class: "form-label"} %><br />
          <%= f.text_area :description , { class: "form-control"} %>
        </div>

        <div class="mb-3">
          <%= f.label "Commiturile de Git:", { class: "form-label"} %><br />
          <%= f.text_field :first_commit, { class: "form-control", placeholder: "Prmul commit..." } %>
        </div>

        <div class="mb-3">
          <%= f.text_field :last_commit, { class: "form-control", placeholder: "Ultimul commit..." } %>
        </div>


        <div class="mb-3">
          <%= f.label "Estimare" %><br />
          <%= f.select :estimation, Task::ESTIMATION_OPTIONS, {}, { class: "form form-group form-select" }%>
        </div>

        <div class="mb-3">
          <%= f.label "Feedback-ul dezvoltatorului:" %><br />
          <%= f.select :developer_feedback, Task::DEVELOPER_FEEDBACK_OPTIONS, {}, { class: "form form-group form-select" }%>
        </div>

        <%# This field is autocompleted with the current users details id%>
        <%= f.hidden_field :user_detail_id, value: @current_user_details.id %>

        <div class="mb-3">
          <%= f.submit "Adaugă", {class: "btn btn-success"} %>
        </div>
      </div>
    </div>
  </div>



<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', [@task.component, @task] %> |
<%= link_to 'Back', component_tasks_path(@task.component) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>First commit</th>
    <th>Last commit</th>
    <th>Estimation</th>
    <th>Developer feedback</th>
    <th>User detail</th>
    <th>Component</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.description %></td>
    <td><%= task.first_commit %></td>
    <td><%= task.last_commit %></td>
    <td><%= task.estimation %></td>
    <td><%= task.developer_feedback %></td>
    <td><%= task.user_detail %></td>
    <td><%= task.component %></td>
    <td><%= link_to 'Show', [task.component, task] %></td>
    <td><%= link_to 'Edit', edit_component_task_path(task.component, task) %></td>
    <td><%= link_to 'Destroy', [task.component, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_component_task_path(params[:component_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', component_tasks_path(@task.component) %>

app/views/tasks/show.html.erb
<div class = "container">
  <p id="notice"><%= notice %></p>
  <div class="card">
    <div class="card-body ">
      <div class="card-header-team text-light rounded">
        <div class="fw-bold"><h1><%= @task.title %></h1></div>
      </div>
      <div class="row mx-1 mb-1">
        <div class="card mb-2">
          <div class="card-body">
            <h6 style="text-align: left;"><%= @task.description %></h6>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <ul class="list-group ">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Echipă responsabilă:
                <span class="lead"><span class="badge bg-primary rounded-pill"><%= "Echipa " + @team.name %></span></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Developer responsabil:
                <span class="lead"><span class="badge bg-primary rounded-pill"><%=@developer.first_name + " " + @developer.last_name %></span></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Git commit-ul inițial:
                <span class="lead"><span class="badge bg-primary rounded-pill">
                <%= @task.first_commit %>
                </span></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Git commit-ul final:
                <span class="lead"><span class="badge bg-primary rounded-pill">
                  <%= @task.last_commit %>
                </span></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Estimare:
                <span class="lead"><span class="badge bg-primary rounded-pill">
                  <%= @task.estimation.to_s + " SP" %>
                </span></span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Activitatea a fost:
                <span class="lead"><span class="badge bg-primary rounded-pill"><%= @feedback_task %></span></span>
              </li>
            </ul>
            <br>
            <div class="row">
              <div class="col ">
                <%= link_to 'Editează activitatea', edit_component_task_path(@task.component, @task),class:"btn btn-success text-white float-start" %>
              </div>
              <div class="col">
                <%= link_to 'Întoarcere la componentă', component_path(@task.component),class:"btn btn-secondary text-white float-end" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style> 
  .vertical-scrollable> .row {
    height: 300px;
    overflow-y: scroll; 
  }

  .btn-subscribe,
  .btn-subscribe:hover,
  .btn-subscribe:active,
  .btn-subscribe:visited,
  .btn-subscribe:focus {
    background-color: #cd201f;
    border-color: #cd201f;
  }

  .btn-destroy,
  .btn-destroy:hover,
  .btn-destroy:active,
  .btn-destroy:visited,
  .btn-destroy:focus {
    background-color: #131418;
    border-color: #131418;
  }

  .card .card-header-team {
  background-color: #212529; 
  border-color: transparent;
  }

  .card-activity {
  background-color: #0077B5; 
  border-color: transparent;
  max-height:63px;
  }

  a {
    color: inherit;
    text-decoration: none;
  }

  a:hover {
    color: inherit;
    text-decoration: none;
  }

  a:active {
    color: inherit;
  }

  a:visited {
    color: inherit;
  }

</style> 