config/routes.rb
Rails.application.routes.draw do
  resources :components do
    resources :tasks
  end
  namespace :component do
    resources :tasks
  end
  resources :user_details
  resources :teams
  resources :meetings do
    resources :logs
  end
  namespace :meeting do
    resources :logs
  end
  resources :appoiments
  resources :meetings do
    member do
      get :toggle_subscribe
      get :toggle_unsubscribe
    end
  end
  devise_for :users
  
  resources :users do
    get :search_logs
  end

  root to: "user#index"
end

app/models/appoiment.rb
class Appoiment < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/controllers/appoiments_controller.rb
class AppoimentsController < ApplicationController
  before_action :set_appoiment, only: %i[ show edit update destroy ]

  # GET /appoiments or /appoiments.json
  def index
    @appoiments = Appoiment.all
  end

  # GET /appoiments/1 or /appoiments/1.json
  def show
  end

  # GET /appoiments/new
  def new
    @appoiment = Appoiment.new
  end

  # GET /appoiments/1/edit
  def edit
  end

  # POST /appoiments or /appoiments.json
  def create
    @appoiment = Appoiment.new(appoiment_params)

    respond_to do |format|
      if @appoiment.save
        format.html { redirect_to @appoiment, notice: "Appoiment was successfully created." }
        format.json { render :show, status: :created, location: @appoiment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appoiments/1 or /appoiments/1.json
  def update
    respond_to do |format|
      if @appoiment.update(appoiment_params)
        format.html { redirect_to @appoiment, notice: "Appoiment was successfully updated." }
        format.json { render :show, status: :ok, location: @appoiment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appoiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appoiments/1 or /appoiments/1.json
  def destroy
    @appoiment.destroy
    respond_to do |format|
      format.html { redirect_to appoiments_url, notice: "Appoiment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appoiment
      @appoiment = Appoiment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appoiment_params
      params.require(:appoiment).permit(:user_id, :meeting_id)
    end
end

app/helpers/appoiments_helper.rb
module AppoimentsHelper
end

app/views/appoiments/_form.html.erb
<%= form_with(model: appoiment) do |form| %>
  <% if appoiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appoiment.errors.count, "error") %> prohibited this appoiment from being saved:</h2>

      <ul>
        <% appoiment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :meeting_id %>
    <%= form.text_field :meeting_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appoiments/edit.html.erb
<h1>Editing Appoiment</h1>

<%= render 'form', appoiment: @appoiment %>

<%= link_to 'Show', @appoiment %> |
<%= link_to 'Back', appoiments_path %>

app/views/appoiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appoiments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Meeting</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appoiments.each do |appoiment| %>
      <tr>
        <td><%= appoiment.user_id %></td>
        <td><%= appoiment.meeting_id %></td>
        <td><%= link_to 'Show', appoiment %></td>
        <td><%= link_to 'Edit', edit_appoiment_path(appoiment) %></td>
        <td><%= link_to 'Destroy', appoiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appoiment', new_appoiment_path %>

app/views/appoiments/new.html.erb
<h1>New Appoiment</h1>

<%= render 'form', appoiment: @appoiment %>

<%= link_to 'Back', appoiments_path %>

app/views/appoiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @appoiment.user_id %>
</p>

<p>
  <strong>Meeting:</strong>
  <%= @appoiment.meeting_id %>
</p>

<%= link_to 'Edit', edit_appoiment_path(@appoiment) %> |
<%= link_to 'Back', appoiments_path %>