config/routes.rb
Rails.application.routes.draw do
  resources :components do
    resources :tasks
  end
  namespace :component do
    resources :tasks
  end
  resources :user_details
  resources :teams
  resources :meetings do
    resources :logs
  end
  namespace :meeting do
    resources :logs
  end
  resources :appoiments
  resources :meetings do
    member do
      get :toggle_subscribe
      get :toggle_unsubscribe
    end
  end
  devise_for :users
  
  resources :users do
    get :search_logs
  end

  root to: "user#index"
end

app/models/log.rb
class Log < ApplicationRecord
  include PgSearch::Model
  
  multisearchable  against: [:title, :content],
    update_if: :title_changed?,
    update_if: :content_changed?
  


  belongs_to :meeting

  validates :severity, inclusion: {in: ['normal', 'critical']} 

  SEVERITY_OPTIONS = [['Normal','normal'],['Critic','critical']]
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_meeting
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET meetings/1/logs
  def index
    @logs = @meeting.logs
  end

  # GET meetings/1/logs/1
  def show
  end

  # GET meetings/1/logs/new
  def new
    @log = @meeting.logs.build
  end

  # GET meetings/1/logs/1/edit
  def edit
  end

  # POST meetings/1/logs
  def create
    @log = @meeting.logs.build(log_params)

    if @log.save
      redirect_to(@log.meeting)
    else
      render action: 'new'
    end
  end

  # PUT meetings/1/logs/1
  def update
    if @log.update_attributes(log_params)
      redirect_to([@log.meeting, @log], notice: 'Log was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE meetings/1/logs/1
  def destroy
    @log.destroy

    redirect_to meeting_logs_url(@meeting)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:meeting_id])
    end

    def set_log
      @log = @meeting.logs.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def log_params
      params.require(:log).permit(:title, :content, :severity, :date, :meeting_id)
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: [@log.meeting, @log]) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='container'>
    <div class="card">
      <div class="card-body " style="text-align: left;">
      <h3 class='card-tytle' style="text-align: center;">Adaugă o nouă notiță ședinței</h3>
        <div class="mb-3">
          <%= f.label "Titlu", { class: "form-label"}  %><br />
          <%= f.text_field :title, { class: "form-control", placeholder: "Titlu..." } %>
        </div>

        <div class="mb-3">
          <%= f.label "Conținut", { class: "form-label"} %><br />
          <%= f.text_area :content , { class: "form-control"} %>
        </div>

        <div class="mb-3">
          <%= f.label "Severitate" %><br />
          <%= f.select :severity, Log::SEVERITY_OPTIONS, {}, { class: "form form-group form-control" }%>
        </div>

        <div class="mb-3">
          <%= f.label "Data" %><br />
          <%= f.date_select :date %>
        </div>

        <div class="mb-3">
          <%= f.submit "Adaugă", {class: "btn btn-primary"} %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', [@log.meeting, @log] %> |
<%= link_to 'Back', meeting_logs_path(@log.meeting) %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Severity</th>
    <th>Date</th>
    <th>Meeting</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logs.each do |log| %>
  <tr>
    <td><%= log.title %></td>
    <td><%= log.content %></td>
    <td><%= log.severity %></td>
    <td><%= log.date %></td>
    <td><%= log.meeting %></td>
    <td><%= link_to 'Show', [log.meeting, log] %></td>
    <td><%= link_to 'Edit', edit_meeting_log_path(log.meeting, log) %></td>
    <td><%= link_to 'Destroy', [log.meeting, log], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Log', new_meeting_log_path(params[:meeting_id]) %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_logs_path(@log.meeting) %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @log.title %>
</p>

<p>
  <b>Content:</b>
  <%= @log.content %>
</p>

<p>
  <b>Severity:</b>
  <%= @log.severity %>
</p>

<p>
  <b>Date:</b>
  <%= @log.date %>
</p>

<p>
  <b>Meeting:</b>
  <%= @log.meeting %>
</p>


<%= link_to 'Edit', edit_meeting_log_path(@log.meeting, @log) %> |
<%= link_to 'Back', meeting_logs_path(@log.meeting) %>